version: "{branch} #{build}"

platform:
  - x64

shallow_clone: true

matrix:
  fast_finish: false

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go get github.com/bradfitz/slice

build_script:
  - go build awesome.go
