version: "{branch} #{build}"

platform:
  - x64

shallow_clone: true

matrix:
  fast_finish: true

clone_folder: c:\gopath\src\github.com\orsinium\awesome-generator

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/orsinium/awesome-generator

build_script:
  - go build awesome.go
